%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\dzedzer1\Desktop\work_documents\3. School
%    work\Lucia\statictemp.xlsx Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2019/03/12 23:35:33

format long   %allows all the digits on the number to be displayed when printing results to screen

%% Import the data for statictemp
[~, ~, raw] = xlsread('C:\Users\dzedzer1\Desktop\work_documents\3. School work\Lucia\statictemp.xlsx','Sheet1','A5:B671');

%% Create output variable
statictemp = reshape([raw{:}],size(raw));

%% Clear temporary variables
clearvars data raw cellVectors;

%% import data for staticpressure

[~, ~, raw] = xlsread('C:\Users\dzedzer1\Desktop\work_documents\3. School work\Lucia\staticpressure.xlsx','Sheet1','A5:B672');

%% Create output variable
staticpressure = reshape([raw{:}],size(raw));

%% Clear temporary variables
clearvars raw;

%% import stagtemp data

[~, ~, raw] = xlsread('C:\Users\dzedzer1\Desktop\work_documents\3. School work\Lucia\stag_temp.xlsx','stag_temp','A5:B672');

%% Create output variable
stagtemp = reshape([raw{:}],size(raw));

%% Clear temporary variables
clearvars raw;

statictemp;
staticpressure;
stagtemp;